export { default as Calendar } from './pages/Calendar';
export { default as Ecommerce } from './pages/Ecommerce'
export { default as Kanban } from './pages/Kanban';
export { default as Orders } from './pages/Orders';
export { default as Employees } from './pages/Employees';
export { default as Editor } from './pages/Editor';
export { default as Customers } from './pages/Customers';
export { default as ColorPicker } from './pages/ColorPicker';
export { default as Area } from './pages/Charts/Area';
export { default as Bar } from './pages/Charts/Bar';
export { default as ColorMapping } from './pages/Charts/ColorMapping';
export { default as Financial } from './pages/Charts/Financial';
export { default as Line } from './pages/Charts/Line';
export { default as Pie } from './pages/Charts/Pie';
export { default as Pyramid } from './pages/Charts/Pyramid';
export { default as Stacked } from './pages/Charts/Stacked';
